import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Runtime client that uses the environment variables managed by Lovable Cloud.
// This exists because the autogenerated client file may get out of sync across environments.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Fail fast in dev so it's obvious why requests are failing.
  // (In production builds, console is dropped by Vite config.)
  // eslint-disable-next-line no-console
  console.error('Missing backend environment variables for Supabase client', {
    hasUrl: !!SUPABASE_URL,
    hasKey: !!SUPABASE_PUBLISHABLE_KEY,
  });
}

export const supabase = createClient<Database>(SUPABASE_URL ?? '', SUPABASE_PUBLISHABLE_KEY ?? '');
